name: PandasSneezePlus
main: hasjamon.block4block.PandasSneezePlus
api-version: 1.21
authors: [HasJamOn, Bahm]
version: 1.0
description: Increases baby panda sneeze rate and allows adult pandas to sneeze.
